### ISSUE TITLE
Ability to turn off reports completely

### ISSUE THREAD

**Issue by forceedge01** [forceedge01/behat-stats-logger#13]
Something like:

```
topReport:
    enabled: false
suiteReport:
    enabled: false
suiteSummaryReport:
    enabled: false
```
