### ISSUE TITLE
Highlight groups based on time

### ISSUE THREAD

**Issue by forceedge01** [forceedge01/behat-stats-logger#4]
```
Context:
  highlight:
    step:
        blue: 5
    scenario:
        red: 60
        yellow: 45
```
